/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.Banco;
import model.bean.ContaCorrente;
import model.dao.BancoDAO;

/**
 *
 * @author douglas
 */
public class TelaSaque extends javax.swing.JFrame {

    /**
     * Creates new form TelaSaque
     */
    public TelaSaque() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spiValor = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCelula20 = new javax.swing.JButton();
        btnCelula40 = new javax.swing.JButton();
        btnCelula50 = new javax.swing.JButton();
        btnCelula100 = new javax.swing.JButton();
        btnCelula300 = new javax.swing.JButton();
        btnCelula600 = new javax.swing.JButton();
        btnCelula900 = new javax.swing.JButton();
        btnCelula1200 = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saque");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor:");

        spiValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spiValor.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Notas Disponiveis R$: 2,5,10,20,50 ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dispensa maxima de 35 celulas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> Selecione a opção desejada <br> ou Digite o valor desejado.</html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spiValor)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spiValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 200));

        btnCelula20.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula20.setText("R$ 20,00");
        btnCelula20.setOpaque(false);
        btnCelula20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula20ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 44));

        btnCelula40.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula40.setText("R$ 40,00");
        btnCelula40.setOpaque(false);
        btnCelula40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula40ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, 44));

        btnCelula50.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula50.setText("R$ 50,00");
        btnCelula50.setOpaque(false);
        btnCelula50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula50ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 44));

        btnCelula100.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula100.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula100.setText("R$ 100,00");
        btnCelula100.setOpaque(false);
        btnCelula100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula100ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula100, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, 44));

        btnCelula300.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula300.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula300.setText("R$ 300,00");
        btnCelula300.setOpaque(false);
        btnCelula300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula300ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula300, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 110, 44));

        btnCelula600.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula600.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula600.setText("R$ 600,00");
        btnCelula600.setOpaque(false);
        btnCelula600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula600ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula600, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 110, 44));

        btnCelula900.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula900.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula900.setText("R$ 900,00");
        btnCelula900.setOpaque(false);
        btnCelula900.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula900ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula900, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 44));

        btnCelula1200.setBackground(new java.awt.Color(255, 255, 255));
        btnCelula1200.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCelula1200.setText("R$ 1200,00");
        btnCelula1200.setOpaque(false);
        btnCelula1200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelula1200ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCelula1200, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 110, 44));

        btnSacar.setBackground(new java.awt.Color(255, 255, 255));
        btnSacar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-saque.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCelula20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula20ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 20);
    }//GEN-LAST:event_btnCelula20ActionPerformed

    private void btnCelula40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula40ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 40);
    }//GEN-LAST:event_btnCelula40ActionPerformed

    private void btnCelula50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula50ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 50);
    }//GEN-LAST:event_btnCelula50ActionPerformed

    private void btnCelula100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula100ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 100);
    }//GEN-LAST:event_btnCelula100ActionPerformed

    private void btnCelula300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula300ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 300);
    }//GEN-LAST:event_btnCelula300ActionPerformed

    private void btnCelula600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula600ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 600);
    }//GEN-LAST:event_btnCelula600ActionPerformed

    private void btnCelula900ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula900ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 900);
    }//GEN-LAST:event_btnCelula900ActionPerformed

    private void btnCelula1200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelula1200ActionPerformed
        spiValor.setValue((int) spiValor.getValue() + 1200);
    }//GEN-LAST:event_btnCelula1200ActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        String numeroConta  =  TelaConta.txtNumeroConta.getText();
        String tipo  = (String) TelaConta.cbTipo.getSelectedItem();
        
        BancoDAO bDAO = new BancoDAO();
        Banco b = new Banco();
        
        b.setNumConta(Integer.parseInt(numeroConta));
        b.setTipo((String) tipo);
        int valor = (int) spiValor.getValue();
        b.setSaldo(valor);
        
        try {
            if (bDAO.checkConta((String) tipo, Integer.parseInt(numeroConta))) {
                if (valor <= 0) {
                    JOptionPane.showMessageDialog(null, "Saque um valor maior que 0");
                }else{
                    double saldo = bDAO.getSaldo(b);
                    if(valor > saldo){
                        JOptionPane.showMessageDialog(null, "Saldo Insulficiente!");
                    }else{
                        bDAO.sacarSaldo(b, (int) b.getSaldo());
                        this.dispose();
                        TelaPrincipal tp = new TelaPrincipal();
                        tp.setVisible(true); 
                    }
                }
               
            } else {
                JOptionPane.showMessageDialog(null, "Tipo ou numero da conta incorreta!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Tipo ou numero da conta incorreta!");
        }
         
    }//GEN-LAST:event_btnSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelula100;
    private javax.swing.JButton btnCelula1200;
    private javax.swing.JButton btnCelula20;
    private javax.swing.JButton btnCelula300;
    private javax.swing.JButton btnCelula40;
    private javax.swing.JButton btnCelula50;
    private javax.swing.JButton btnCelula600;
    private javax.swing.JButton btnCelula900;
    private javax.swing.JButton btnSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spiValor;
    // End of variables declaration//GEN-END:variables
}
