/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JComboBox;
import model.bean.Banco;
import model.dao.BancoDAO;
import static view.TelaConta.cbTipo;
import static view.TelaConta.txtNumeroConta;

/**
 *
 * @author douglas
 */
public class TelaSaldo extends javax.swing.JFrame {

    /**
     * Creates new form TelaSaldo
     */
    public TelaSaldo() {
        initComponents();
       
        String numeroConta  =  TelaConta.txtNumeroConta.getText();
        String tipo  = (String) TelaConta.cbTipo.getSelectedItem();
        
        BancoDAO bDAO = new BancoDAO();
        Banco b = new Banco();
        
        b.setNumConta(Integer.parseInt(numeroConta));
        double saldo = bDAO.getSaldo(b);
        lblSaldo.setText(Double.toString(saldo));
        lblSaldoDis.setText(Double.toString(saldo));
        lblSaldoTotal.setText(Double.toString(saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldoBloq = new javax.swing.JLabel();
        lblSaldoDis = new javax.swing.JLabel();
        lblSaldoTotal = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saldo");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Saldo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 19, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Saldo");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 98, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Saldo Bloqueado");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 133, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Saldo Disponível");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 168, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Saldo Total");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 203, -1, -1));

        lblSaldo.setBackground(new java.awt.Color(255, 255, 255));
        lblSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("0");
        lblSaldo.setToolTipText("");
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 98, 90, -1));

        lblSaldoBloq.setBackground(new java.awt.Color(255, 255, 255));
        lblSaldoBloq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaldoBloq.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoBloq.setText("0");
        lblSaldoBloq.setToolTipText("");
        getContentPane().add(lblSaldoBloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 133, 90, -1));

        lblSaldoDis.setBackground(new java.awt.Color(255, 255, 255));
        lblSaldoDis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaldoDis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoDis.setText("0");
        lblSaldoDis.setToolTipText("");
        getContentPane().add(lblSaldoDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 168, 90, -1));

        lblSaldoTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblSaldoTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSaldoTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoTotal.setText("0");
        lblSaldoTotal.setToolTipText("");
        getContentPane().add(lblSaldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 203, 90, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/return.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-saldo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true); 
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoBloq;
    private javax.swing.JLabel lblSaldoDis;
    private javax.swing.JLabel lblSaldoTotal;
    // End of variables declaration//GEN-END:variables
}
